// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRj6QcC13EgGgn8X5FUCdNHIJbLbF-WIU',
    appId: '1:1097242350126:web:3fa67376fca36c1805c5bf',
    messagingSenderId: '1097242350126',
    projectId: 'apprastreogt',
    authDomain: 'apprastreogt.firebaseapp.com',
    storageBucket: 'apprastreogt.appspot.com',
    measurementId: 'G-JE1ZHZQ4NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkAtZ521Ge8ZFU5UPaH5Y_IkjUd-yG2CY',
    appId: '1:1097242350126:android:624dad1894bc219e05c5bf',
    messagingSenderId: '1097242350126',
    projectId: 'apprastreogt',
    storageBucket: 'apprastreogt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1OxmCBcC5dC0M63hGkbC57fSUhJlLVi4',
    appId: '1:1097242350126:ios:6594bec3d7c344f205c5bf',
    messagingSenderId: '1097242350126',
    projectId: 'apprastreogt',
    storageBucket: 'apprastreogt.appspot.com',
    androidClientId:
        '1097242350126-96i8v8vtn3glmh8okabrk89smmpc0osa.apps.googleusercontent.com',
    iosClientId:
        '1097242350126-bc0bageepive2jchh1cj6qkng6567m4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.rastreogt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1OxmCBcC5dC0M63hGkbC57fSUhJlLVi4',
    appId: '1:1097242350126:ios:0e53ade8a4ff7c8105c5bf',
    messagingSenderId: '1097242350126',
    projectId: 'apprastreogt',
    storageBucket: 'apprastreogt.appspot.com',
    androidClientId:
        '1097242350126-96i8v8vtn3glmh8okabrk89smmpc0osa.apps.googleusercontent.com',
    iosClientId:
        '1097242350126-1v183jnob1nmv35lvq2qoa09hb06je7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.rastreogt.RunnerTests',
  );
}
